apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: reader
rules:
  - apiGroups: ["*"]
    resources: ["deployments", "configmaps", "pods", "secrets", "services", "namespaces"]
    verbs: ["get", "list", "watch", "create"] #this gives the user permissions on what they can do 